main:
	g++  --std=c++17 -I/opt/homebrew/Cellar/boost/1.86.0_2/include  -I/Users/sergey/Desktop/hseCppHomeWork/Common/ -o server main.cpp Server.cpp /Users/sergey/Desktop/hseCppHomeWork/Common/helpers.cpp
